Many to many
MikolajTanski/CocktailsApp pull request #12
Opened 2022-12-30 18:48 UTC by MikolajTanski

2023-01-02 16:22 UTC, Szczepp approved these changes

2023-01-02 16:26 UTC, Szczepp requested changes
Przyda nam się też `ICollecton<Ingredient>` w `CocktailRecipe`. Będziemy raczej wyszukiwać koktajle po składnikach niż składniki po koktajlach. Poza tym gitówa.

2023-01-02 19:56 UTC, MikolajTanski commented
> Przyda nam się też `ICollecton<Ingredient>` w `CocktailRecipe`. Będziemy raczej wyszukiwać koktajle po składnikach niż składniki po koktajlach. Poza tym gitówa.

dzięki za poprawienie :) rano wrzucę!

2023-01-04 20:38 UTC, closed without merging

2023-01-04 20:40 UTC, Szczepp commented
Po dyskusji na discordzie okazuje się, że obecna relacje jest już wystarczająca, poprzedni komentarz nieaktualny.